default['pw_cookbook_repo']['alias'] = '/cookbooks'
default['pw_cookbook_repo']['dir'] = '/data/cookbooks'
default['pw_cookbook_repo']['importdir'] = '/data/cookbooks/import'
default['pw_cookbook_repo']['owner'] = 'ubuntu'
default['pw_cookbook_repo']['group'] = 'ubuntu'
default['pw_cookbook_repo']['berks-api-url'] = 'http://berks-api'
default['pw_cookbook_repo']['berks-api-rebuild'] = '60'
default['pw_cookbook_repo']['berks-api-universe-url'] = '/universe'
